{
 "title": "PEPPER / HTTP / INCOMING / DRILL",
 "tags": [
  "http",
  "incoming",
  "pepper"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobname", "label": "jobname", "query": "pepper_exporter_k8s" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=~\"$jobname\"}, appId)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(http_summary_seconds_count{app=\"$app\"}, method)"
   },
   {
    "name": "url",
    "label": "url",
    "query": "label_values(http_summary_seconds_count{app=\"$app\", method=\"$method\"}, url)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(http_summary_seconds_count{app=\"$app\", method=\"$method\", url=~\"$url\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "http - $url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "url" },
  {
   "title": "并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (http_concurrent_gauge{appId=~\"$app\", method=~\"$method\", url=~\"$url\", pod=~\"$pod\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P90 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "repeat": "motan",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.9\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.99\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.999\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_summary_seconds_count{appId=~\"$app\", method=~\"$method\", url=~\"$url\", pod=~\"$pod\"}[3m])) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX - $url",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.99999\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P90 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.9\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"})",
     "legendFormat": "P90"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.9\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 24h)",
     "legendFormat": "P90 - Last Day"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.9\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 7d)",
     "legendFormat": "P90 - Last Week"
    }
   ]
  },
  {
   "title": "P99 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.99\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"})",
     "legendFormat": "P99"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.99\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 24h)",
     "legendFormat": "P99 - Last Day"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.99\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 7d)",
     "legendFormat": "P99 - Last Week"
    }
   ]
  },
  {
   "title": "P999 - $method $url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.999\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"})",
     "legendFormat": "P999"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.999\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 24h)",
     "legendFormat": "P999 - Last Day"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\", quantile=\"0.999\", method=~\"$method\", url=\"$url\", pod=~\"$pod\"} offset 7d)",
     "legendFormat": "P999 - Last Week"
    }
   ]
  },
  {
   "title": "not 2XX By Instance - 2m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(http_status_summary_seconds_count{app=\"$app\", method=~\"$method\", url=\"$url\", pod=~\"$pod\", status!~\"2..\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}