{
 "title": "PEPPER / MYBATIS",
 "tags": [
  "mybatis",
  "pepper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=\"pepper_exporter_k8s\"}, appId)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS - By Class",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(class) (rate(app_mapper_summary_seconds_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "并发 - By Class",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (class) (app_mapper_concurrent_gauge{appId=~\"$app\"})",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "P99 - By Class",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_mapper_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "ERR - Mybatis - 3m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(class) (increase(app_mapper_err_counter{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  { "title": "By Method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "QPS - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(operation) (rate(app_mapper_summary_seconds_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P99 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_mapper_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P999 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_mapper_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ERR - 3m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(operation) (increase(app_mapper_err_counter{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "QPS - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(app_mapper_summary_seconds_count{app=~\"$app\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99 - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_mapper_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999 - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(app_mapper_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ERR - 3m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (increase(app_mapper_err_counter{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}