{
 "title": "PEPPER / HTTP / INCOMING",
 "tags": [
  "http",
  "incoming",
  "pepper"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobname", "label": "jobname", "query": "pepper_exporter_k8s" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=~\"$jobname\"}, appId)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method, url) (rate(http_summary_seconds_count{appId=~\"$app\"}[3m])) >0",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "MAX P99 By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=\"$app\",quantile=\"0.99\"}) by (method, url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "并发 By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (http_concurrent_gauge{app=~\"$app\"} offset 1m ) by (method, url)",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "not 2XX - 2m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_status_summary_seconds_count{app=~\"$app\", status!~\"2..\"}[2m]))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_summary_seconds_count{appId=~\"$app\"}[3m])) >0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{appId=\"$app\",quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (http_concurrent_gauge{app=~\"$app\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "not 2XX By Instance - 2m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(http_status_summary_seconds_count{app=~\"$app\", status!~\"2..\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "请点击服务名进入详情",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(method, url) (rate(http_summary_seconds_count{app=~\"$app\"}[3m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "((sum\n  by(url) (increase(http_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(url) (increase(http_summary_seconds_count{appId=~\"$app\"}[10m]))) * 100) > 0",
     "legendFormat": "错误率"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\",quantile=\"0.99\"}) by (url)",
     "legendFormat": "P99"
    },
    {
     "expr": "max(http_summary_seconds{app=\"$app\",quantile=\"0.999\"}) by (url)",
     "legendFormat": "P999"
    },
    {
     "expr": "sum (http_concurrent_gauge{app=~\"$app\"} offset 1m ) by (url)",
     "legendFormat": "并发"
    }
   ]
  }
 ]
}