{
 "title": "PEPPER / JEDIS",
 "tags": [
  "jedis",
  "pepper"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=\"pepper_exporter_k8s\"}, appId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace) (rate(jedis_summary_seconds_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}"
      },
      {
       "expr": "sum by(namespace) (rate(jedisCluster_summary_seconds_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "cluster::{{namespace}}"
      }
     ]
    },
    {
     "title": "并发 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (jedisCluster_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "sum by (namespace) (jedis_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "P99 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(jedisCluster_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace)",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "max(jedis_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace)",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "ERR - JedisClient / JedisClusterClient - 3m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace) (increase(jedisCluster_err_counter{appId=~\"$app\"}[3m]))",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "sum by(namespace) (increase(jedis_err_counter{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "JedisCluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "QPS - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, method) (rate(jedisCluster_summary_seconds_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "cluster::{{namespace}}::{{method}}"
    }
   ]
  },
  {
   "title": "P99 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(jedisCluster_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace, method)",
     "legendFormat": "cluster::{{namespace}}::{{method}}"
    }
   ]
  },
  {
   "title": "P999 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(jedisCluster_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (namespace, method)",
     "legendFormat": "cluster::{{namespace}}::{{method}}"
    }
   ]
  },
  {
   "title": "ERR - 3m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, operation) (increase(jedisCluster_err_counter{appId=~\"$app\"}[3m]))",
     "legendFormat": "cluster::{{namespace}}-{{operation}}"
    }
   ]
  },
  {
   "title": "QPS - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, pod) (rate(jedisCluster_summary_seconds_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "cluster::{{namespace}}::{{pod}}"
    }
   ]
  },
  {
   "title": "P99 - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(jedisCluster_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace, pod)",
     "legendFormat": "cluster::{{namespace}}::{{pod}}"
    }
   ]
  },
  {
   "title": "P999 - By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(jedisCluster_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (namespace, pod)",
     "legendFormat": "cluster::{{namespace}}::{{pod}}"
    }
   ]
  },
  {
   "title": "ERR - 3m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, pod) (increase(jedisCluster_err_counter{appId=~\"$app\"}[3m]))",
     "legendFormat": "cluster::{{namespace}}::{{pod}}"
    }
   ]
  },
  {
   "title": "JedisStandalone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS - By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, method) (rate(jedis_summary_seconds_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}::{{method}}"
      }
     ]
    },
    {
     "title": "P99 - By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(jedis_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace, method)",
       "legendFormat": "std::{{namespace}}::{{method}}"
      }
     ]
    },
    {
     "title": "P999 - By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(jedis_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (namespace, method)",
       "legendFormat": "std::{{namespace}}::{{method}}"
      }
     ]
    },
    {
     "title": "ERR - 3m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, operation) (increase(jedis_err_counter{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}-{{operation}}"
      }
     ]
    },
    {
     "title": "QPS - By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, pod) (rate(jedis_summary_seconds_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}::{{pod}}"
      }
     ]
    },
    {
     "title": "P99 - By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(jedis_summary_seconds{quantile=\"0.99\", app=~\"$app\"}) by (namespace, pod)",
       "legendFormat": "std::{{namespace}}::{{pod}}"
      }
     ]
    },
    {
     "title": "P999 - By Instance",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(jedis_summary_seconds{quantile=\"0.999\", app=~\"$app\"}) by (namespace, pod)",
       "legendFormat": "std::{{namespace}}::{{pod}}"
      }
     ]
    },
    {
     "title": "ERR - 3m",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace, pod) (increase(jedis_err_counter{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}::{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}